// This file is generated by scripts/build-rn-tokens.js. Do not edit manually.

export const tokenMeta = {
  "name": "CloudSea Design Tokens",
  "version": "1.0.0",
  "defaultTheme": "dark"
} as const;

export const lightTokens = {
  "color": {
    "bg": "#eef7ff",
    "bgPage": "#eef7ff",
    "bgCard": "rgba(255, 255, 255, 0.88)",
    "bgDark": "rgba(11, 47, 91, 0.08)",
    "bgSubtle": "rgba(11, 47, 91, 0.06)",
    "bgOverlay": "rgba(11, 47, 91, 0.18)",
    "primary": "#1677c8",
    "primarySoft": "rgba(22, 119, 200, 0.10)",
    "primaryBorder": "rgba(22, 119, 200, 0.24)",
    "success": "#1f8a3b",
    "successSoft": "rgba(31, 138, 59, 0.12)",
    "danger": "#d94848",
    "dangerStrong": "#b4232c",
    "dangerSoft": "rgba(217, 72, 72, 0.12)",
    "warning": "#b7791f",
    "warningSoft": "rgba(183, 121, 31, 0.12)",
    "text": "#172033",
    "textStrong": "#08111f",
    "textSecondary": "#475569",
    "textWeak": "#64748b",
    "textMuted": "#7c8796",
    "border": "rgba(23, 32, 51, 0.14)",
    "borderDefault": "rgba(23, 32, 51, 0.14)",
    "borderSubtle": "rgba(23, 32, 51, 0.08)",
    "shadow": "rgba(15, 23, 42, 0.14)",
    "white": "#ffffff"
  },
  "spacing": {
    "xs": 4,
    "sm": 6,
    "md": 8,
    "lg": 12,
    "xl": 16,
    "2xl": 20,
    "3xl": 24
  },
  "radius": {
    "sm": 4,
    "md": 6,
    "lg": 8,
    "xl": 12,
    "2xl": 14,
    "pill": 999
  },
  "font": {
    "xs": 10,
    "sm": 12,
    "md": 14,
    "lg": 17,
    "xl": 22,
    "2xl": 28
  }
} as const;

export const darkTokens = {
  "color": {
    "bg": "#0b2f5b",
    "bgPage": "#0b2f5b",
    "bgCard": "rgba(14, 20, 32, 0.72)",
    "bgDark": "rgba(0, 0, 0, 0.25)",
    "bgSubtle": "rgba(255, 255, 255, 0.06)",
    "bgOverlay": "rgba(0, 0, 0, 0.6)",
    "primary": "#3aa4ff",
    "primarySoft": "rgba(58, 164, 255, 0.12)",
    "primaryBorder": "rgba(58, 164, 255, 0.3)",
    "success": "#28a745",
    "successSoft": "rgba(40, 167, 69, 0.18)",
    "danger": "#ff6b6b",
    "dangerStrong": "#dc3545",
    "dangerSoft": "rgba(220, 53, 69, 0.18)",
    "warning": "#f0ad4e",
    "warningSoft": "rgba(240, 173, 78, 0.18)",
    "text": "#eef4ff",
    "textStrong": "#ffffff",
    "textSecondary": "#aab4c5",
    "textWeak": "#8899aa",
    "textMuted": "#6c757d",
    "border": "rgba(173, 199, 255, 0.18)",
    "borderDefault": "rgba(173, 199, 255, 0.18)",
    "borderSubtle": "rgba(173, 199, 255, 0.08)",
    "shadow": "rgba(0, 0, 0, 0.25)",
    "white": "#ffffff"
  },
  "spacing": {
    "xs": 4,
    "sm": 6,
    "md": 8,
    "lg": 12,
    "xl": 16,
    "2xl": 20,
    "3xl": 24
  },
  "radius": {
    "sm": 4,
    "md": 6,
    "lg": 8,
    "xl": 12,
    "2xl": 14,
    "pill": 999
  },
  "font": {
    "xs": 10,
    "sm": 12,
    "md": 14,
    "lg": 17,
    "xl": 22,
    "2xl": 28
  }
} as const;

export const themes = {
  light: lightTokens,
  dark: darkTokens,
} as const;

export type CloudSeaThemeName = keyof typeof themes;
export type CloudSeaTokens = (typeof themes)[CloudSeaThemeName];
